name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - run: go build ./...
      - run: go test -count=1 -timeout 600s ./...
      - run: go vet ./...

  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - run: make tidy
      - run: git diff --name-only --exit-code

  release-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - name: 跨平台构建发布版本
        run: |
          tags=$(cat build-tags.txt)
          echo "release tags: $tags"
          GOOS=linux GOARCH=amd64 go build -o /dev/null -tags "$tags" ./cmd/tailcat
          GOOS=linux GOARCH=arm64 go build -o /dev/null -tags "$tags" ./cmd/tailcat
          GOOS=linux GOARCH=arm GOARM=7 go build -o /dev/null -tags "$tags" ./cmd/tailcat
          GOOS=windows GOARCH=amd64 go build -o /dev/null -tags "$tags" ./cmd/tailcat
          GOOS=windows GOARCH=arm64 go build -o /dev/null -tags "$tags" ./cmd/tailcat

  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - name: 构建 js/wasm
        run: go build -o /tmp/tailcat-web.wasm ./web
        env:
          GOOS: js
          GOARCH: wasm
      - name: 检查 Google Chrome
        run: |
          which google-chrome
          google-chrome --version
      - name: 运行浏览器测试
        run: go test ./web/ -v -count=1 -timeout 300s --run-headless-browser-tests

  goreleaser:
    needs: [test, tidy, release-tags, wasm]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # for the changelog
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
